export default {
	Name: "String",
	Description: "String",
	Texture: "String",
	$Skins: ["StardewValley.GameData.Buildings.BuildingSkin"],
	DrawShadow: "Boolean",
	UpgradeSignTile: "Vector2",
	UpgradeSignHeight: "Single",
	Size: "Point",
	FadeWhenBehind: "Boolean",
	SourceRect: "Rectangle",
	SeasonOffset: "Point",
	DrawOffset: "Vector2",
	SortTileOffset: "Single",
	$CollisionMap: "String",
	$AdditionalPlacementTiles: ["StardewValley.GameData.Buildings.BuildingPlacementTile"],
	$BuildingType: "String",
	$Builder: "String",
	$BuildCondition: "String",
	BuildDays: "Int32",
	BuildCost: "Int32",
	$BuildMaterials: ["StardewValley.GameData.Buildings.BuildingMaterial"],
	$BuildingToUpgrade: "String",
	MagicalConstruction: "Boolean",
	BuildMenuDrawOffset: "Point",
	HumanDoor: "Point",
	AnimalDoor: "Rectangle",
	AnimalDoorOpenDuration: "Single",
	$AnimalDoorOpenSound: "String",
	AnimalDoorCloseDuration: "Single",
	$AnimalDoorCloseSound: "String",
	$NonInstancedIndoorLocation: "String",
	$IndoorMap: "String",
	$IndoorMapType: "String",
	MaxOccupants: "Int32",
	$ValidOccupantTypes: ["String"],
	AllowAnimalPregnancy: "Boolean",
	$IndoorItemMoves: ["StardewValley.GameData.Buildings.IndoorItemMove"],
	$IndoorItems: ["StardewValley.GameData.Buildings.IndoorItemAdd"],
	$AddMailOnBuild: ["String"],
	$MetaData: {"String": "String"},
	$ModData: {"String": "String"},
	HayCapacity: "Int32",
	$Chests: ["StardewValley.GameData.Buildings.BuildingChest"],
	$DefaultAction: "String",
	AdditionalTilePropertyRadius: "Int32",
	AllowsFlooringUnderneath: "Boolean",
	$ActionTiles: ["StardewValley.GameData.Buildings.BuildingActionTile"],
	$TileProperties: ["StardewValley.GameData.Buildings.BuildingTileProperty"],
	$ItemConversions: ["StardewValley.GameData.Buildings.BuildingItemConversion"],
	$DrawLayers: ["StardewValley.GameData.Buildings.BuildingDrawLayer"],
	$CustomFields: {"String": "String"}
}