export default {
	"Seasons": ["Int32"],
	"DaysInPhase": ["Int32"],
	"RegrowDays": "Int32",
	"IsRaised": "Boolean",
	"IsPaddyCrop": "Boolean",
	"NeedsWatering": "Boolean",
	"$PlantableLocationRules": ["StardewValley.GameData.PlantableRule"],
	"HarvestItemId": "String",
	"HarvestMinStack": "Int32",
	"HarvestMaxStack": "Int32",
	"HarvestMaxIncreasePerFarmingLevel": "Single",
	"ExtraHarvestChance": "Double",
	"HarvestMethod": "Int32",
	"HarvestMinQuality": "Int32",
	"$HarvestMaxQuality": "Int32",
	"$TintColors": ["String"],
	"Texture": "String",
	"SpriteIndex": "Int32",
	"CountForMonoculture": "Boolean",
	"CountForPolyculture": "Boolean",
	"$CustomFields": {"String": "String"}
};