export default {
	"$Condition": "String",
	"$WindowBorderTexture": "String",
	"$WindowBorderSourceRect": "Rectangle",
	"$PortraitBackgroundTexture": "String",
	"$PortraitBackgroundSourceRect": "Rectangle",
	"$DialogueBackgroundTexture": "String",
	"$DialogueBackgroundSourceRect": "Rectangle",
	"$DialogueColor": "String",
	"$DialogueShadowColor": "String",
	"$ItemRowBackgroundTexture": "String",
	"$ItemRowBackgroundSourceRect": "Rectangle",
	"$ItemRowBackgroundHoverColor": "String",
	"$ItemRowTextColor": "String",
	"$ItemIconBackgroundTexture": "String",
	"$ItemIconBackgroundSourceRect": "Rectangle",
	"$ScrollUpTexture": "String",
	"$ScrollUpSourceRect": "Rectangle",
	"$ScrollDownTexture": "String",
	"$ScrollDownSourceRect": "Rectangle",
	"$ScrollBarFrontTexture": "String",
	"$ScrollBarFrontSourceRect": "Rectangle",
	"$ScrollBarBackTexture": "String",
	"$ScrollBarBackSourceRect": "Rectangle"
};