export default {
	"$DisplayName": "String",
	"$House": "String",
	"Gender": "Int32",
	"PurchasePrice": "Int32",
	"SellPrice": "Int32",
	"$ShopTexture": "String",
	"ShopSourceRect": "Rectangle",
	"$ShopDisplayName": "String",
	"$ShopDescription": "String",
	"$ShopMissingBuildingDescription": "String",
	"$RequiredBuilding": "String",
	"$UnlockCondition": "String",
	"$AlternatePurchaseTypes": ["StardewValley.GameData.FarmAnimals.AlternatePurchaseAnimals"],
	"$EggItemIds": ["String"],
	"IncubationTime": "Int32",
	"IncubatorParentSheetOffset": "Int32",
	"$BirthText": "String",
	"DaysToMature": "Int32",
	"CanGetPregnant": "Boolean",
	"DaysToProduce": "Int32",
	"HarvestType": "Int32",
	"$HarvestTool": "String",
	"$ProduceItemIds": [
		"StardewValley.GameData.FarmAnimals.FarmAnimalProduce"
	],
	"$DeluxeProduceItemIds": [
		"StardewValley.GameData.FarmAnimals.FarmAnimalProduce"
	],
	"ProduceOnMature": "Boolean",
	"FriendshipForFasterProduce": "Int32",
	"DeluxeProduceMinimumFriendship": "Int32",
	"DeluxeProduceCareDivisor": "Single",
	"DeluxeProduceLuckMultiplier": "Single",
	"CanEatGoldenCrackers": "Boolean",
	"ProfessionForHappinessBoost": "Int32",
	"ProfessionForQualityBoost": "Int32",
	"ProfessionForFasterProduce": "Int32",
	"$Sound": "String",
	"$BabySound": "String",
	"Texture": "String",
	"$HarvestedTexture": "String",
	"$BabyTexture": "String",
	"UseFlippedRightForLeft": "Boolean",
	"SpriteWidth": "Int32",
	"SpriteHeight": "Int32",
	"UseDoubleUniqueAnimationFrames": "Boolean",
	"SleepFrame": "Int32",
	"EmoteOffset": "Point",
	"SwimOffset": "Point",
	"$Skins": [
		"StardewValley.GameData.FarmAnimals.FarmAnimalSkin"
	],
	"$ShadowWhenBabySwims": "StardewValley.GameData.FarmAnimals.FarmAnimalShadowData",
	"$ShadowWhenBaby": "StardewValley.GameData.FarmAnimals.FarmAnimalShadowData",
	"$ShadowWhenAdultSwims": "StardewValley.GameData.FarmAnimals.FarmAnimalShadowData",
	"$ShadowWhenAdult": "StardewValley.GameData.FarmAnimals.FarmAnimalShadowData",
	"$Shadow": "StardewValley.GameData.FarmAnimals.FarmAnimalShadowData",
	"CanSwim": "Boolean",
	"BabiesFollowAdults": "Boolean",
	"GrassEatAmount": "Int32",
	"HappinessDrain": "Int32",
	"UpDownPetHitboxTileSize": "Vector2",
	"LeftRightPetHitboxTileSize": "Vector2",
	"BabyUpDownPetHitboxTileSize": "Vector2",
	"BabyLeftRightPetHitboxTileSize": "Vector2",
	"$StatToIncrementOnProduce": [
		"StardewValley.GameData.StatIncrement"
	],
	"ShowInSummitCredits": "Boolean",
	"$CustomFields": {"String": "String"}
}